In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
## Define the vocabulary size
voc_size=10000

In [5]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [6]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[4437, 2840, 3907, 8665],
 [4437, 2840, 3907, 8745],
 [4437, 8883, 3907, 1669],
 [4178, 9609, 1984, 894, 8924],
 [4178, 9609, 1984, 894, 5216],
 [8739, 4437, 2645, 3907, 5748],
 [6209, 5491, 3992, 894]]

In [7]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding
#from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [8]:
import numpy as np

In [9]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 4437 2840 3907 8665]
 [   0    0    0    0 4437 2840 3907 8745]
 [   0    0    0    0 4437 8883 3907 1669]
 [   0    0    0 4178 9609 1984  894 8924]
 [   0    0    0 4178 9609 1984  894 5216]
 [   0    0    0 8739 4437 2645 3907 5748]
 [   0    0    0    0 6209 5491 3992  894]]


In [10]:
## feature representation
dim=10

In [11]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

/opt/homebrew/lib/python3.10/site-packages/keras/src/layers/core/embedding.py:97: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [12]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [13]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 85ms/step


array([[[ 0.00496323,  0.0402422 , -0.00411613,  0.04237496,
         -0.03225763, -0.01797453, -0.00412286, -0.01075153,
          0.03382752,  0.01650136],
        [ 0.00496323,  0.0402422 , -0.00411613,  0.04237496,
         -0.03225763, -0.01797453, -0.00412286, -0.01075153,
          0.03382752,  0.01650136],
        [ 0.00496323,  0.0402422 , -0.00411613,  0.04237496,
         -0.03225763, -0.01797453, -0.00412286, -0.01075153,
          0.03382752,  0.01650136],
        [ 0.00496323,  0.0402422 , -0.00411613,  0.04237496,
         -0.03225763, -0.01797453, -0.00412286, -0.01075153,
          0.03382752,  0.01650136],
        [ 0.04705591,  0.02299062, -0.02229872,  0.0111294 ,
          0.01121742,  0.04181173, -0.03319088, -0.00505506,
          0.02644059,  0.00686646],
        [ 0.0221785 ,  0.01914981, -0.00032728, -0.04876481,
         -0.02930291,  0.04428095,  0.01350558, -0.03024817,
          0.03125394,  0.00592766],
        [-0.04361376,  0.04045141,  0.02465384, -0.0

In [14]:
embedded_docs[0]

array([   0,    0,    0,    0, 4437, 2840, 3907, 8665], dtype=int32)

In [18]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step


array([[[ 0.00496323,  0.0402422 , -0.00411613,  0.04237496,
         -0.03225763, -0.01797453, -0.00412286, -0.01075153,
          0.03382752,  0.01650136],
        [ 0.00496323,  0.0402422 , -0.00411613,  0.04237496,
         -0.03225763, -0.01797453, -0.00412286, -0.01075153,
          0.03382752,  0.01650136],
        [ 0.00496323,  0.0402422 , -0.00411613,  0.04237496,
         -0.03225763, -0.01797453, -0.00412286, -0.01075153,
          0.03382752,  0.01650136],
        [ 0.00496323,  0.0402422 , -0.00411613,  0.04237496,
         -0.03225763, -0.01797453, -0.00412286, -0.01075153,
          0.03382752,  0.01650136],
        [ 0.04705591,  0.02299062, -0.02229872,  0.0111294 ,
          0.01121742,  0.04181173, -0.03319088, -0.00505506,
          0.02644059,  0.00686646],
        [ 0.0221785 ,  0.01914981, -0.00032728, -0.04876481,
         -0.02930291,  0.04428095,  0.01350558, -0.03024817,
          0.03125394,  0.00592766],
        [-0.04361376,  0.04045141,  0.02465384, -0.0